[tools]
rust = "stable"

[env]
PROJECT_NAME = "{{ config_root | basename }}"

[tasks.commit]
run = "uv run --with-requirements requirements.txt -- scripts/deploy.py commit"

[tasks.tag]
run = "uv run --with-requirements requirements.txt -- python scripts/deploy.py tag"
